### ISSUE TITLE
小白问个。。。

### ISSUE THREAD

**Issue by Theoneee** [arvinljw/AFBaseLibrary#1]
怎么获取实体啊。。。不是List

**Comment by arvinljw** [comment]
获取什么实体？列表中的数据？

**Comment by Theoneee** [comment]
唔~~~~   以前后台由返回那种没有  private int event;  private JsonElement data;  JsonElement那种数据，全都是在外面的。。。和 event一级的那种。。不知道我这样说你能不能明白  - -

**Comment by arvinljw** [comment]
在列表中可以这样

```
if (page == AFConstant.REFRESH_FIRST_PAGE) {
    mItems.clear();
}
mItems.addAll(data);
refreshLoadComplete(isSuccess(data));
```
dataj是后台返回的数据，如果不是列表，你就可以自己保存这个数据去操作就好了，这些实体是自己写，然后在列表中通过泛型来对应的。具体你可以简单看看smaple中怎么使用的。
